#
# /*
#  * Copyright (c) 2022. Omni Data Science Inc and it's subsidiaries - All Rights Reserved
#  *  Unauthorized copying of this file, via any medium is strictly prohibited Proprietary and
#  *  confidential
#  * Written by Ebot Tabi <e@voyancehq.com>, 9/2/2022
#  */
#
#
#
camunda:
bpm:
default-serialization-format: application/json
authorization:
enabled: false
filter:
create: All
history-level: activity
id-generator: strong
database:
schema-update: true
type: h2
webapp:
index-redirect-enabled: false
admin-user:
id: demo
password: demo
login:
enabled: true
user-id: admin

springdoc:
packagesToScan: com.example.workflow.rest
pathsToMatch: /**

spring:
jpa:
open-in-view: true
hibernate:
ddl-auto: create-drop
show-sql: true
properties:
hibernate:
dialect: org.hibernate.dialect.H2Dialect
defer-datasource-initialization: true
h2:
console:
enabled: true
path: /h2-ui
main:
allow-bean-definition-overriding: true
datasource:
url: jdbc:h2:~/brume-camunda
username: sa
password:
hikari:
maximum-pool-size: 2
driver-class-name: org.h2.Driver
  server.port=1011
  app.devMode=true
  app.aes_salt=0#l%jI>f^JY(vOk#
  //mvc.view.404=/index.html
  app.name=Sigma Server
  app.max-file-size=20480
  app.support_163_music=true
  app.support_gist=true
  com.blade.logger.org.sql2o=all
  sso.url=http://127.0.0.1:4000
  redirect.url=http://127.0.0.1:3000
